import '../models/workout_node.dart';

class LibraryService {
  static Map<String, List<LibraryExercise>> getFullLibrary() {
    return {
      "Chest": [
        LibraryExercise(name: "Flat Barbell Bench Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Incline Barbell Bench Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Decline Barbell Bench Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Flat Dumbbell Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Incline Dumbbell Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Decline Dumbbell Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Close-Grip Barbell Bench Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Wide-Grip Barbell Bench Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Dumbbell Flyes", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Incline Dumbbell Flyes", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Cable Crossovers (High-to-Low)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Cable Crossovers (Low-to-High)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Flat Machine Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Incline Machine Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Pec Deck Machine", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Weighted Chest Dips", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Dumbbell Pullover", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Floor Press (Barbell)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Svend Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Hammer Strength Chest Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Landmine Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Guillotine Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Pushups (Diamond)", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Pushups (Wide)", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Weighted Pushups", trackingIndex: TrackingType.weightReps.index),
      ],
      "Back": [
        LibraryExercise(name: "Conventional Deadlift", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Sumo Deadlift", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Rack Pulls", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Bent Over Barbell Row", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Bent Over Dumbbell Row", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Single-Arm Dumbbell Row", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "T-Bar Row", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Meadows Row", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Seal Row", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Pendlay Row", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Lat Pulldown (Wide Grip)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Lat Pulldown (Close Grip)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Lat Pulldown (Behind Neck)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Lat Pulldown (Neutral Grip)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Seated Cable Row (Wide)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Seated Cable Row (V-Bar)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Straight Arm Lat Pulldown", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Barbell Pullover", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Hyperextensions (Back Extensions)", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Weighted Hyperextensions", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Good Mornings", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Machine Row", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Hammer Strength Row", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Face Pulls", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Barbell Shrugs", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Dumbbell Shrugs", trackingIndex: TrackingType.weightReps.index),
      ],
      "Legs": [
        LibraryExercise(name: "Barbell Back Squat", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Barbell Front Squat", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Low Bar Squat", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Goblet Squat", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Hack Squat Machine", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Leg Press (45 Degree)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Horizontal Leg Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Bulgarian Split Squat", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Dumbbell Lunges", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Barbell Lunges", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Walking Lunges", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Step-Ups", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Leg Extensions", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Seated Leg Curls", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Lying Leg Curls", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Standing Leg Curls", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Romanian Deadlift (Barbell)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Romanian Deadlift (Dumbbell)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Stiff-Legged Deadlift", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Glute-Ham Raise", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Adductor Machine", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Abductor Machine", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Sissy Squat", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Zercher Squat", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Box Squat", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Pistol Squat", trackingIndex: TrackingType.repsOnly.index),
      ],
      "Shoulders": [
        LibraryExercise(name: "Overhead Press (Standing)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Military Press (Seated)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Dumbbell Shoulder Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Arnold Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Machine Shoulder Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Push Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Behind the Neck Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Dumbbell Lateral Raise", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Cable Lateral Raise", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Machine Lateral Raise", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Dumbbell Front Raise", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Barbell Front Raise", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Cable Front Raise", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Rear Delt Flyes (Dumbbell)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Rear Delt Flyes (Machine)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Rear Delt Flyes (Cable)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Upright Row (Barbell)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Upright Row (Dumbbell)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Bus Drivers", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Bradford Press", trackingIndex: TrackingType.weightReps.index),
      ],
      "Arms": [
        LibraryExercise(name: "Barbell Bicep Curl", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "EZ-Bar Bicep Curl", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Dumbbell Bicep Curl", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Hammer Curl", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Preacher Curl (Barbell)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Preacher Curl (Dumbbell)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Incline Dumbbell Curl", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Concentration Curl", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Spider Curl", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Cable Bicep Curl", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "21s (Barbell)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Zottman Curl", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Reverse Barbell Curl", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Wrist Curl (Barbell)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Tricep Pushdown (Cable)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Tricep Pushdown (Rope)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Skullcrushers (EZ-Bar)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Overhead Dumbbell Extension", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Overhead Cable Extension", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Dips (Tricep Focus)", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Weighted Dips (Triceps)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Tricep Kickbacks (Dumbbell)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Close-Grip Bench Press", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "JM Press", trackingIndex: TrackingType.weightReps.index),
      ],
      "Calisthenics & Skills": [
        LibraryExercise(name: "Pull Ups", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Chin Ups", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Muscle Up", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Muscle Up (Slow)", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Handstand Hold", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Handstand Pushups", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Handstand Pushups (Deficit)", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Planche Lean", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Tuck Planche Hold", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Straddle Planche Hold", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Full Planche Hold", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Front Lever Hold", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Back Lever Hold", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "L-Sit Hold", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "V-Sit Hold", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Human Flag", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Explosive Pull Ups", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Archer Pull Ups", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "One Arm Pull Up Progression", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Typewriter Pull Ups", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Skin the Cat", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Korean Dips", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Dragon Flag", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Pseudo Planche Pushups", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Ring Dips", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Ring Muscle Ups", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Impossible Dips", trackingIndex: TrackingType.repsOnly.index),
      ],
      "Core": [
        LibraryExercise(name: "Plank", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Side Plank", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Weighted Plank", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Hanging Leg Raises", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Hanging Knee Raises", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Toes to Bar", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Ab Wheel Rollouts", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Weighted Ab Wheel", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Cable Crunch", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Russian Twists", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Weighted Russian Twists", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Woodchoppers (Cable)", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Dragon Flag", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Dead Bug", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Bird Dog", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Hollow Body Hold", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Bicycle Crunches", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Reverse Crunches", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "L-Sit", trackingIndex: TrackingType.time.index),
      ],
      "Glutes": [
        LibraryExercise(name: "Barbell Hip Thrusts", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Glute Bridge", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Kas Glute Bridge", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Cable Glute Kickbacks", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Abductor Machine", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Sumo Squat", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Clamshells", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Frog Pumps", trackingIndex: TrackingType.repsOnly.index),
      ],
      "Calves & Neck": [
        LibraryExercise(name: "Standing Calf Raises", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Seated Calf Raises", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Donkey Calf Raises", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Leg Press Calf Raises", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Tibialis Raises", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Barbell Neck Extension", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Lying Plate Neck Flexion", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Harness Neck Work", trackingIndex: TrackingType.weightReps.index),
        LibraryExercise(name: "Isometric Neck Hold", trackingIndex: TrackingType.time.index),
      ],
      "Cardio": [
        LibraryExercise(name: "Running (Outdoors)", trackingIndex:TrackingType.distance.index),
        LibraryExercise(name: "Treadmill Run", trackingIndex: TrackingType.distance.index),
        LibraryExercise(name: "Treadmill (Incline Walk)", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Cycling (Outdoors)", trackingIndex: TrackingType.distance.index),
        LibraryExercise(name: "Stationary Bike", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Rowing Machine", trackingIndex: TrackingType.distance.index),
        LibraryExercise(name: "Elliptical", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Stairmaster", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Jump Rope", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "Burpees", trackingIndex: TrackingType.repsOnly.index),
        LibraryExercise(name: "Swimming", trackingIndex: TrackingType.distance.index),
        LibraryExercise(name: "Shadow Boxing", trackingIndex: TrackingType.time.index),
        LibraryExercise(name: "HIIT Sprints", trackingIndex: TrackingType.distance.index),
      ],
    };
  }
}