import '../models/workout_node.dart';

class LibraryService {
  static Map<String, List<LibraryExercise>> getFullLibrary() {
    return {
      "Chest": [
        LibraryExercise(name: "Flat Barbell Bench Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Incline Barbell Bench Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Decline Barbell Bench Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Flat Dumbbell Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Incline Dumbbell Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Decline Dumbbell Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Close-Grip Barbell Bench Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Wide-Grip Barbell Bench Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Dumbbell Flyes", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Incline Dumbbell Flyes", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Cable Crossovers (High-to-Low)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Cable Crossovers (Low-to-High)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Flat Machine Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Incline Machine Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Pec Deck Machine", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Weighted Chest Dips", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Dumbbell Pullover", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Floor Press (Barbell)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Svend Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Hammer Strength Chest Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Landmine Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Guillotine Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Pushups (Diamond)", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Pushups (Wide)", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Weighted Pushups", trackingType: TrackingType.weightReps),
      ],
      "Back": [
        LibraryExercise(name: "Conventional Deadlift", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Sumo Deadlift", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Rack Pulls", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Bent Over Barbell Row", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Bent Over Dumbbell Row", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Single-Arm Dumbbell Row", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "T-Bar Row", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Meadows Row", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Seal Row", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Pendlay Row", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Lat Pulldown (Wide Grip)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Lat Pulldown (Close Grip)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Lat Pulldown (Behind Neck)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Lat Pulldown (Neutral Grip)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Seated Cable Row (Wide)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Seated Cable Row (V-Bar)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Straight Arm Lat Pulldown", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Barbell Pullover", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Hyperextensions (Back Extensions)", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Weighted Hyperextensions", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Good Mornings", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Machine Row", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Hammer Strength Row", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Face Pulls", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Barbell Shrugs", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Dumbbell Shrugs", trackingType: TrackingType.weightReps),
      ],
      "Legs": [
        LibraryExercise(name: "Barbell Back Squat", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Barbell Front Squat", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Low Bar Squat", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Goblet Squat", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Hack Squat Machine", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Leg Press (45 Degree)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Horizontal Leg Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Bulgarian Split Squat", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Dumbbell Lunges", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Barbell Lunges", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Walking Lunges", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Step-Ups", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Leg Extensions", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Seated Leg Curls", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Lying Leg Curls", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Standing Leg Curls", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Romanian Deadlift (Barbell)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Romanian Deadlift (Dumbbell)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Stiff-Legged Deadlift", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Glute-Ham Raise", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Adductor Machine", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Abductor Machine", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Sissy Squat", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Zercher Squat", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Box Squat", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Pistol Squat", trackingType: TrackingType.repsOnly),
      ],
      "Shoulders": [
        LibraryExercise(name: "Overhead Press (Standing)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Military Press (Seated)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Dumbbell Shoulder Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Arnold Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Machine Shoulder Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Push Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Behind the Neck Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Dumbbell Lateral Raise", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Cable Lateral Raise", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Machine Lateral Raise", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Dumbbell Front Raise", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Barbell Front Raise", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Cable Front Raise", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Rear Delt Flyes (Dumbbell)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Rear Delt Flyes (Machine)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Rear Delt Flyes (Cable)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Upright Row (Barbell)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Upright Row (Dumbbell)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Bus Drivers", trackingType: TrackingType.time),
        LibraryExercise(name: "Bradford Press", trackingType: TrackingType.weightReps),
      ],
      "Arms": [
        LibraryExercise(name: "Barbell Bicep Curl", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "EZ-Bar Bicep Curl", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Dumbbell Bicep Curl", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Hammer Curl", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Preacher Curl (Barbell)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Preacher Curl (Dumbbell)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Incline Dumbbell Curl", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Concentration Curl", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Spider Curl", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Cable Bicep Curl", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "21s (Barbell)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Zottman Curl", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Reverse Barbell Curl", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Wrist Curl (Barbell)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Tricep Pushdown (Cable)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Tricep Pushdown (Rope)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Skullcrushers (EZ-Bar)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Overhead Dumbbell Extension", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Overhead Cable Extension", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Dips (Tricep Focus)", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Weighted Dips (Triceps)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Tricep Kickbacks (Dumbbell)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Close-Grip Bench Press", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "JM Press", trackingType: TrackingType.weightReps),
      ],
      "Calisthenics & Skills": [
        LibraryExercise(name: "Pull Ups", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Chin Ups", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Muscle Up", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Muscle Up (Slow)", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Handstand Hold", trackingType: TrackingType.time),
        LibraryExercise(name: "Handstand Pushups", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Handstand Pushups (Deficit)", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Planche Lean", trackingType: TrackingType.time),
        LibraryExercise(name: "Tuck Planche Hold", trackingType: TrackingType.time),
        LibraryExercise(name: "Straddle Planche Hold", trackingType: TrackingType.time),
        LibraryExercise(name: "Full Planche Hold", trackingType: TrackingType.time),
        LibraryExercise(name: "Front Lever Hold", trackingType: TrackingType.time),
        LibraryExercise(name: "Back Lever Hold", trackingType: TrackingType.time),
        LibraryExercise(name: "L-Sit Hold", trackingType: TrackingType.time),
        LibraryExercise(name: "V-Sit Hold", trackingType: TrackingType.time),
        LibraryExercise(name: "Human Flag", trackingType: TrackingType.time),
        LibraryExercise(name: "Explosive Pull Ups", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Archer Pull Ups", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "One Arm Pull Up Progression", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Typewriter Pull Ups", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Skin the Cat", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Korean Dips", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Dragon Flag", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Pseudo Planche Pushups", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Ring Dips", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Ring Muscle Ups", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Impossible Dips", trackingType: TrackingType.repsOnly),
      ],
      "Core": [
        LibraryExercise(name: "Plank", trackingType: TrackingType.time),
        LibraryExercise(name: "Side Plank", trackingType: TrackingType.time),
        LibraryExercise(name: "Weighted Plank", trackingType: TrackingType.time),
        LibraryExercise(name: "Hanging Leg Raises", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Hanging Knee Raises", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Toes to Bar", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Ab Wheel Rollouts", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Weighted Ab Wheel", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Cable Crunch", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Russian Twists", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Weighted Russian Twists", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Woodchoppers (Cable)", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Dragon Flag", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Dead Bug", trackingType: TrackingType.time),
        LibraryExercise(name: "Bird Dog", trackingType: TrackingType.time),
        LibraryExercise(name: "Hollow Body Hold", trackingType: TrackingType.time),
        LibraryExercise(name: "Bicycle Crunches", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Reverse Crunches", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "L-Sit", trackingType: TrackingType.time),
      ],
      "Glutes": [
        LibraryExercise(name: "Barbell Hip Thrusts", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Glute Bridge", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Kas Glute Bridge", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Cable Glute Kickbacks", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Abductor Machine", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Sumo Squat", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Clamshells", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Frog Pumps", trackingType: TrackingType.repsOnly),
      ],
      "Calves & Neck": [
        LibraryExercise(name: "Standing Calf Raises", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Seated Calf Raises", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Donkey Calf Raises", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Leg Press Calf Raises", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Tibialis Raises", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Barbell Neck Extension", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Lying Plate Neck Flexion", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Harness Neck Work", trackingType: TrackingType.weightReps),
        LibraryExercise(name: "Isometric Neck Hold", trackingType: TrackingType.time),
      ],
      "Cardio": [
        LibraryExercise(name: "Running (Outdoors)", trackingType: TrackingType.distance),
        LibraryExercise(name: "Treadmill Run", trackingType: TrackingType.distance),
        LibraryExercise(name: "Treadmill (Incline Walk)", trackingType: TrackingType.time),
        LibraryExercise(name: "Cycling (Outdoors)", trackingType: TrackingType.distance),
        LibraryExercise(name: "Stationary Bike", trackingType: TrackingType.time),
        LibraryExercise(name: "Rowing Machine", trackingType: TrackingType.distance),
        LibraryExercise(name: "Elliptical", trackingType: TrackingType.time),
        LibraryExercise(name: "Stairmaster", trackingType: TrackingType.time),
        LibraryExercise(name: "Jump Rope", trackingType: TrackingType.time),
        LibraryExercise(name: "Burpees", trackingType: TrackingType.repsOnly),
        LibraryExercise(name: "Swimming", trackingType: TrackingType.distance),
        LibraryExercise(name: "Shadow Boxing", trackingType: TrackingType.time),
        LibraryExercise(name: "HIIT Sprints", trackingType: TrackingType.distance),
      ],
    };
  }
}