// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/custom_protocol.dart';
import 'models/goal_node.dart';
import 'models/workout_log.dart';
import 'models/workout_node.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5391456175230400220),
    name: 'GoalNode',
    lastPropertyId: const obx_int.IdUid(8, 4722859382961758948),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5419726589228525965),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5957689107567554867),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3468301901147291609),
        name: 'typeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1103039267992361242),
        name: 'currentWeight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9197052696326697112),
        name: 'targetWeight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2487996990930233349),
        name: 'weightStep',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4502725520854733199),
        name: 'totalSessions',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4722859382961758948),
        name: 'completedSessions',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 3464219401384539183),
        name: 'children',
        targetId: const obx_int.IdUid(1, 5391456175230400220),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 7519553410864308563),
        name: 'sets',
        targetId: const obx_int.IdUid(4, 7399304807380505350),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8315263967946897502),
    name: 'WorkoutLog',
    lastPropertyId: const obx_int.IdUid(4, 118427517800830421),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6629190812025929902),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2943064485772794778),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8688050740789899992),
        name: 'exerciseName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 118427517800830421),
        name: 'muscleGroup',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 5404582854078675399),
        name: 'performedSets',
        targetId: const obx_int.IdUid(4, 7399304807380505350),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2062288298101410463),
    name: 'WorkoutNode',
    lastPropertyId: const obx_int.IdUid(10, 8884678089084243580),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5586779259402126830),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2633728282814289888),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8318980691276120445),
        name: 'typeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6248627912717057310),
        name: 'trackingIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2034944599738584817),
        name: 'restTime',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5150816923346741052),
        name: 'interExerciseRest',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8802079275716076164),
        name: 'muscleGroup',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8884678089084243580),
        name: 'protocolId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 6851795456588437109),
        relationTarget: 'CustomProtocol',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(4, 1854053538483659513),
        name: 'children',
        targetId: const obx_int.IdUid(3, 2062288298101410463),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(5, 1934228833631167816),
        name: 'sets',
        targetId: const obx_int.IdUid(4, 7399304807380505350),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7399304807380505350),
    name: 'WorkoutSet',
    lastPropertyId: const obx_int.IdUid(4, 685527478610085349),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 868351317927102195),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2651980766900392210),
        name: 'value',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7550364745997980272),
        name: 'weight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 685527478610085349),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 8860872662423777712),
    name: 'CustomProtocol',
    lastPropertyId: const obx_int.IdUid(4, 5920543652844262617),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4850041679599861506),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1913609192515049944),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 696834328279942427),
        name: 'script',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5920543652844262617),
        name: 'scopeIndex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 8860872662423777712),
    lastIndexId: const obx_int.IdUid(1, 6851795456588437109),
    lastRelationId: const obx_int.IdUid(5, 1934228833631167816),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [7765645518388265976, 3422544439003629388],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    GoalNode: obx_int.EntityDefinition<GoalNode>(
      model: _entities[0],
      toOneRelations: (GoalNode object) => [],
      toManyRelations: (GoalNode object) => {
        obx_int.RelInfo<GoalNode>.toMany(1, object.id): object.children,
        obx_int.RelInfo<GoalNode>.toMany(2, object.id): object.sets,
      },
      getId: (GoalNode object) => object.id,
      setId: (GoalNode object, int id) {
        object.id = id;
      },
      objectToFB: (GoalNode object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addInt64(2, object.typeIndex);
        fbb.addFloat64(3, object.currentWeight);
        fbb.addFloat64(4, object.targetWeight);
        fbb.addFloat64(5, object.weightStep);
        fbb.addInt64(6, object.totalSessions);
        fbb.addInt64(7, object.completedSessions);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final typeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final currentWeightParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final targetWeightParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final weightStepParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final totalSessionsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final completedSessionsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = GoalNode(
          id: idParam,
          title: titleParam,
          typeIndex: typeIndexParam,
          currentWeight: currentWeightParam,
          targetWeight: targetWeightParam,
          weightStep: weightStepParam,
          totalSessions: totalSessionsParam,
          completedSessions: completedSessionsParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<GoalNode>(
          object.children,
          store,
          obx_int.RelInfo<GoalNode>.toMany(1, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<GoalNode>(
          object.sets,
          store,
          obx_int.RelInfo<GoalNode>.toMany(2, object.id),
        );
        return object;
      },
    ),
    WorkoutLog: obx_int.EntityDefinition<WorkoutLog>(
      model: _entities[1],
      toOneRelations: (WorkoutLog object) => [],
      toManyRelations: (WorkoutLog object) => {
        obx_int.RelInfo<WorkoutLog>.toMany(3, object.id): object.performedSets,
      },
      getId: (WorkoutLog object) => object.id,
      setId: (WorkoutLog object, int id) {
        object.id = id;
      },
      objectToFB: (WorkoutLog object, fb.Builder fbb) {
        final exerciseNameOffset = fbb.writeString(object.exerciseName);
        final muscleGroupOffset = object.muscleGroup == null
            ? null
            : fbb.writeString(object.muscleGroup!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.date.millisecondsSinceEpoch);
        fbb.addOffset(2, exerciseNameOffset);
        fbb.addOffset(3, muscleGroupOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = WorkoutLog()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..date = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
          )
          ..exerciseName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..muscleGroup = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 10);
        obx_int.InternalToManyAccess.setRelInfo<WorkoutLog>(
          object.performedSets,
          store,
          obx_int.RelInfo<WorkoutLog>.toMany(3, object.id),
        );
        return object;
      },
    ),
    WorkoutNode: obx_int.EntityDefinition<WorkoutNode>(
      model: _entities[2],
      toOneRelations: (WorkoutNode object) => [object.protocol],
      toManyRelations: (WorkoutNode object) => {
        obx_int.RelInfo<WorkoutNode>.toMany(4, object.id): object.children,
        obx_int.RelInfo<WorkoutNode>.toMany(5, object.id): object.sets,
      },
      getId: (WorkoutNode object) => object.id,
      setId: (WorkoutNode object, int id) {
        object.id = id;
      },
      objectToFB: (WorkoutNode object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final muscleGroupOffset = object.muscleGroup == null
            ? null
            : fbb.writeString(object.muscleGroup!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addInt64(2, object.typeIndex);
        fbb.addInt64(3, object.trackingIndex);
        fbb.addInt64(4, object.restTime);
        fbb.addInt64(5, object.interExerciseRest);
        fbb.addOffset(6, muscleGroupOffset);
        fbb.addInt64(9, object.protocol.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final typeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final trackingIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final restTimeParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final interExerciseRestParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final muscleGroupParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final object = WorkoutNode(
          id: idParam,
          title: titleParam,
          typeIndex: typeIndexParam,
          trackingIndex: trackingIndexParam,
          restTime: restTimeParam,
          interExerciseRest: interExerciseRestParam,
          muscleGroup: muscleGroupParam,
        );
        object.protocol.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        object.protocol.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<WorkoutNode>(
          object.children,
          store,
          obx_int.RelInfo<WorkoutNode>.toMany(4, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<WorkoutNode>(
          object.sets,
          store,
          obx_int.RelInfo<WorkoutNode>.toMany(5, object.id),
        );
        return object;
      },
    ),
    WorkoutSet: obx_int.EntityDefinition<WorkoutSet>(
      model: _entities[3],
      toOneRelations: (WorkoutSet object) => [],
      toManyRelations: (WorkoutSet object) => {},
      getId: (WorkoutSet object) => object.id,
      setId: (WorkoutSet object, int id) {
        object.id = id;
      },
      objectToFB: (WorkoutSet object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.value);
        fbb.addFloat64(2, object.weight);
        fbb.addBool(3, object.isCompleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final valueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final weightParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final object = WorkoutSet(
          id: idParam,
          value: valueParam,
          weight: weightParam,
          isCompleted: isCompletedParam,
        );

        return object;
      },
    ),
    CustomProtocol: obx_int.EntityDefinition<CustomProtocol>(
      model: _entities[4],
      toOneRelations: (CustomProtocol object) => [],
      toManyRelations: (CustomProtocol object) => {},
      getId: (CustomProtocol object) => object.id,
      setId: (CustomProtocol object, int id) {
        object.id = id;
      },
      objectToFB: (CustomProtocol object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final scriptOffset = fbb.writeString(object.script);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, scriptOffset);
        fbb.addInt64(3, object.scopeIndex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final scriptParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final scopeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = CustomProtocol(
          id: idParam,
          title: titleParam,
          script: scriptParam,
          scopeIndex: scopeIndexParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [GoalNode] entity fields to define ObjectBox queries.
class GoalNode_ {
  /// See [GoalNode.id].
  static final id = obx.QueryIntegerProperty<GoalNode>(
    _entities[0].properties[0],
  );

  /// See [GoalNode.title].
  static final title = obx.QueryStringProperty<GoalNode>(
    _entities[0].properties[1],
  );

  /// See [GoalNode.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<GoalNode>(
    _entities[0].properties[2],
  );

  /// See [GoalNode.currentWeight].
  static final currentWeight = obx.QueryDoubleProperty<GoalNode>(
    _entities[0].properties[3],
  );

  /// See [GoalNode.targetWeight].
  static final targetWeight = obx.QueryDoubleProperty<GoalNode>(
    _entities[0].properties[4],
  );

  /// See [GoalNode.weightStep].
  static final weightStep = obx.QueryDoubleProperty<GoalNode>(
    _entities[0].properties[5],
  );

  /// See [GoalNode.totalSessions].
  static final totalSessions = obx.QueryIntegerProperty<GoalNode>(
    _entities[0].properties[6],
  );

  /// See [GoalNode.completedSessions].
  static final completedSessions = obx.QueryIntegerProperty<GoalNode>(
    _entities[0].properties[7],
  );

  /// see [GoalNode.children]
  static final children = obx.QueryRelationToMany<GoalNode, GoalNode>(
    _entities[0].relations[0],
  );

  /// see [GoalNode.sets]
  static final sets = obx.QueryRelationToMany<GoalNode, WorkoutSet>(
    _entities[0].relations[1],
  );
}

/// [WorkoutLog] entity fields to define ObjectBox queries.
class WorkoutLog_ {
  /// See [WorkoutLog.id].
  static final id = obx.QueryIntegerProperty<WorkoutLog>(
    _entities[1].properties[0],
  );

  /// See [WorkoutLog.date].
  static final date = obx.QueryDateProperty<WorkoutLog>(
    _entities[1].properties[1],
  );

  /// See [WorkoutLog.exerciseName].
  static final exerciseName = obx.QueryStringProperty<WorkoutLog>(
    _entities[1].properties[2],
  );

  /// See [WorkoutLog.muscleGroup].
  static final muscleGroup = obx.QueryStringProperty<WorkoutLog>(
    _entities[1].properties[3],
  );

  /// see [WorkoutLog.performedSets]
  static final performedSets = obx.QueryRelationToMany<WorkoutLog, WorkoutSet>(
    _entities[1].relations[0],
  );
}

/// [WorkoutNode] entity fields to define ObjectBox queries.
class WorkoutNode_ {
  /// See [WorkoutNode.id].
  static final id = obx.QueryIntegerProperty<WorkoutNode>(
    _entities[2].properties[0],
  );

  /// See [WorkoutNode.title].
  static final title = obx.QueryStringProperty<WorkoutNode>(
    _entities[2].properties[1],
  );

  /// See [WorkoutNode.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<WorkoutNode>(
    _entities[2].properties[2],
  );

  /// See [WorkoutNode.trackingIndex].
  static final trackingIndex = obx.QueryIntegerProperty<WorkoutNode>(
    _entities[2].properties[3],
  );

  /// See [WorkoutNode.restTime].
  static final restTime = obx.QueryIntegerProperty<WorkoutNode>(
    _entities[2].properties[4],
  );

  /// See [WorkoutNode.interExerciseRest].
  static final interExerciseRest = obx.QueryIntegerProperty<WorkoutNode>(
    _entities[2].properties[5],
  );

  /// See [WorkoutNode.muscleGroup].
  static final muscleGroup = obx.QueryStringProperty<WorkoutNode>(
    _entities[2].properties[6],
  );

  /// See [WorkoutNode.protocol].
  static final protocol = obx.QueryRelationToOne<WorkoutNode, CustomProtocol>(
    _entities[2].properties[7],
  );

  /// see [WorkoutNode.children]
  static final children = obx.QueryRelationToMany<WorkoutNode, WorkoutNode>(
    _entities[2].relations[0],
  );

  /// see [WorkoutNode.sets]
  static final sets = obx.QueryRelationToMany<WorkoutNode, WorkoutSet>(
    _entities[2].relations[1],
  );
}

/// [WorkoutSet] entity fields to define ObjectBox queries.
class WorkoutSet_ {
  /// See [WorkoutSet.id].
  static final id = obx.QueryIntegerProperty<WorkoutSet>(
    _entities[3].properties[0],
  );

  /// See [WorkoutSet.value].
  static final value = obx.QueryIntegerProperty<WorkoutSet>(
    _entities[3].properties[1],
  );

  /// See [WorkoutSet.weight].
  static final weight = obx.QueryDoubleProperty<WorkoutSet>(
    _entities[3].properties[2],
  );

  /// See [WorkoutSet.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<WorkoutSet>(
    _entities[3].properties[3],
  );
}

/// [CustomProtocol] entity fields to define ObjectBox queries.
class CustomProtocol_ {
  /// See [CustomProtocol.id].
  static final id = obx.QueryIntegerProperty<CustomProtocol>(
    _entities[4].properties[0],
  );

  /// See [CustomProtocol.title].
  static final title = obx.QueryStringProperty<CustomProtocol>(
    _entities[4].properties[1],
  );

  /// See [CustomProtocol.script].
  static final script = obx.QueryStringProperty<CustomProtocol>(
    _entities[4].properties[2],
  );

  /// See [CustomProtocol.scopeIndex].
  static final scopeIndex = obx.QueryIntegerProperty<CustomProtocol>(
    _entities[4].properties[3],
  );
}
